name = "Limbdark"
uuid = "01eff828-7024-11e9-3df0-8b77921d67e3"
authors = ["Eric Agol <agol@uw.edu>", "Rodrigo Luger <rodluger@gmail.com>", "Daniel Foreman-Mackey <foreman.mackey@gmail.com>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
SpecialFunctions = "1.6"
julia = "1"
